---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis
  labels:
    app: app-redis
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-redis
  template:
    metadata:
      labels:
        app: app-redis
    spec:
      containers:
        - name: container-redis
          image: dan1elhughes/casa-s-redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: config-node-env
            - secretRef:
                name: secrets-error-tracking
            - secretRef:
                name: secrets-redis
