apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-scheduler-tick
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler-tick
              image: buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl --verbose --fail -sSL -X PUT http://service-scheduler.default.svc.cluster.local:3000/tick
          restartPolicy: Never
