---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sunset
  labels:
    app: app-sunset
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-sunset
  template:
    metadata:
      labels:
        app: app-sunset
    spec:
      containers:
        - name: container-sunset
          image: dan1elhughes/casa-s-sunset:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: config-node-env
            - secretRef:
                name: secrets-error-tracking
            - secretRef:
                name: secrets-sunset
