apiVersion: v1
kind: Service
metadata:
  name: service-meross
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 5000
  selector:
    app: app-meross
