---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hue
  labels:
    app: app-hue
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-hue
  template:
    metadata:
      labels:
        app: app-hue
    spec:
      containers:
        - name: container-hue
          image: dan1elhughes/casa-s-hue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: HUE_IP
              valueFrom:
                secretKeyRef:
                  name: secrets-hue
                  key: hue_ip
            - name: HUE_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-hue
                  key: hue_user
            - name: HUE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets-hue
                  key: hue_key
