---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hue
  labels:
    app: app-hue
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-hue
  template:
    metadata:
      labels:
        app: app-hue
    spec:
      containers:
        - name: container-hue
          image: dan1elhughes/casa-s-hue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
