---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-device-manager
  labels:
    app: app-device-manager
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-device-manager
  template:
    metadata:
      labels:
        app: app-device-manager
    spec:
      containers:
        - name: container-device-manager
          image: dan1elhughes/casa-s-device-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: SERVICE_HUE_URL
              value: "http://service-hue.default.svc.cluster.local:3000"
            - name: SERVICE_DEVICE_MANAGER_URL
              value: "http://service-device-manager.default.svc.cluster.local:3000"
            - name: SERVICE_REDIS_URL
              value: "http://service-redis.default.svc.cluster.local:3000"
            - name: SERVICE_IFTTT_URL
              value: "http://service-ifttt.default.svc.cluster.local:3000"
            - name: SERVICE_SLACK_URL
              value: "http://service-slack.default.svc.cluster.local:3000"
