---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-device-manager
  labels:
    app: app-device-manager
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-device-manager
  template:
    metadata:
      labels:
        app: app-device-manager
    spec:
      containers:
        - name: container-device-manager
          image: dan1elhughes/casa-s-device-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: config-service-urls
            - configMapRef:
                name: config-node-env
            - secretRef:
                name: secrets-error-tracking
