---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # Cache is valid for 24 hours

- name: Install Docker
  shell: curl -sSL https://get.docker.com | sh
  args:
    warn: false
    creates: /usr/bin/docker

- name: Add user to docker group
  notify:
    - reboot
  user:
    name: pi
    groups: docker
    append: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Install Docker python library
  pip:
    name: docker

# REBOOT DEVICES IF THIS FAILS ON FIRST RUN
# ansible all -m reboot -i infrastructure/inventory --become
- name: Login Pi user to Docker Hub
  become: false
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
