---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ifttt
  labels:
    app: app-ifttt
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-ifttt
  template:
    metadata:
      labels:
        app: app-ifttt
    spec:
      containers:
        - name: container-ifttt
          image: dan1elhughes/casa-s-ifttt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: config-node-env
            - secretRef:
                name: secrets-ifttt
            - secretRef:
                name: secrets-loggly
