---
- name: Add pi user to the sudoers
  copy:
    dest: "/etc/sudoers.d/pi"
    content: "pi ALL=(ALL) NOPASSWD: ALL"
    mode: 0440

- name: Create .ssh directory
  file:
    path: /home/pi/.ssh
    state: directory

- name: Fetch authorized SSH keys from GitHub
  become: false
  get_url:
    url: https://github.com/dan1elhughes.keys
    dest: /home/pi/.ssh/authorized_keys
    mode: "0644"

- name: Disable password-only SSH
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Disable root SSH
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present

- name: Use 1.1.1.1 for DNS
  notify:
    - reboot
  lineinfile:
    dest: /etc/dhcpcd.conf
    line: "static domain_name_servers=1.1.1.1 1.0.0.1"
    state: present

- name: Disable MOTD
  file:
    path: /etc/motd
    state: absent

- name: Disable power LED
  notify:
    - reboot
  blockinfile:
    path: /boot/config.txt
    block: |
      # Disable power LED.
      # dtparam=act_led_trigger=none
      # dtparam=act_led_activelow=on

- name: Create update script
  template:
    src: "../templates/update.sh"
    dest: "/home/pi/update.sh"
    mode: 0764
    owner: "pi"
    group: "pi"

- name: Configure apt mirror
  template:
    src: "../templates/sources.list"
    dest: "/etc/apt/sources.list"
