---
- name: Add pi user to the sudoers
  copy:
    dest: "/etc/sudoers.d/pi"
    content: "pi ALL=(ALL) NOPASSWD: ALL"
    mode: 0440

- name: Fetch auth program
  get_url:
    url: https://raw.githubusercontent.com/dan1elhughes/auth/master/auth.sh
    dest: /usr/local/bin/auth
    mode: "0755"

- name: Enable auth program
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysCommand "
    line: "AuthorizedKeysCommand /usr/local/bin/auth"
    state: present

- name: Auth as nobody
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysCommandUser"
    line: "AuthorizedKeysCommandUser nobody"
    state: present

- name: Disable password-only SSH
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Disable root SSH
  notify:
    - restart ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present

- name: Use 1.1.1.1 for DNS
  notify:
    - reboot
  lineinfile:
    dest: /etc/dhcpcd.conf
    line: "static domain_name_servers=1.1.1.1 1.0.0.1"
    state: present

- name: Disable MOTD
  file:
    path: /etc/motd
    state: absent

- name: Create update script
  template:
    src: "../templates/update.sh"
    dest: "/home/pi/update.sh"
    mode: 0764
    owner: "pi"
    group: "pi"

- name: Configure apt mirror
  template:
    src: "../templates/sources.list"
    dest: "/etc/apt/sources.list"

- name: Set swap size to 2GB
  notify:
    - reboot
  lineinfile:
    dest: /etc/dphys-swapfile
    regexp: "^CONF_SWAPSIZE="
    line: "CONF_SWAPSIZE=2048"
    state: present
